---
title: "02 - Analysis 2"
author: "Selin Jessa [[selin.jessa@mail.mcgill.ca](mailto:selin.jessa@mail.mcgill.ca)]"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: flatly
    css: ../include/style.css
    toc: yes
    toc_depth: 4
    number_sections: true
    df_print: paged
    includes:
      before_body: ../include/header.html
      after_body:  ../include/footer.html
---

<!-- FRONT MATTER, insert configuration info -->

```{r header, echo = FALSE, results = 'asis', warning = FALSE}

# Index of the document
# ...determines name of the subfolder of `outputs` and `figures`
doc_id <- "02"

suppressMessages(library(here))

# Knit child document with header
res <- knitr::knit_child(here("include", "header.Rmd"), envir = environment(), quiet = TRUE)
cat(res, sep = '\n')

```

<!-- END OF FRONT MATTER -->


# Overview

This is an example of the second analysis in a project, which loads some
outputs produced by the first.

# Libraries

```{r libs, warning = FALSE, message = FALSE, echo = TRUE, cache = FALSE}

library(ggplot2)
library(tidyverse)

```


# Data dependencies

This chunk is wrapped in `<div class="fold o"></div>` to produce a toggle button:

<div class="fold o">
```{r load_data}

mtcars2 <- rr_read_tsv(here("output", "01", "mtcars.tsv"))

```
</div>


# Analysis

We can use the `rr_ggplot` wrapper to save source data alongside the resulting
ggplot, as long as we specify the number of the plot in the chunk.

```{r figure2, echo_fig = TRUE}

mtcars2 %>% 
    rr_ggplot(1, aes(x = disp, y = wt)) +
    geom_line() +
    theme_bw()

mtcars2 %>% 
    rr_ggplot(2, aes(x = disp, y = wt)) +
    geom_point() +
    theme_bw()

```

<!-- END MATTER, insert reproducibility info -->

```{r footer, echo = FALSE, results = 'asis', warning = FALSE, cache = FALSE}

# Knit child document with header
res <- knitr::knit_child(here("include", "footer.Rmd"), envir = environment(), quiet = TRUE)
cat(res, sep = '\n')

```

<!-- END OF END MATTER -->
